// LCK 레전드 선수 데이터베이스
// 이미지 URL은 Leaguepedia 또는 공식 사진을 사용합니다

const players = {
    top: [
        {
            id: 'marin',
            name: 'MaRin',
            realName: '장경환',
            team: 'SKT T1 (2015)',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/4/47/SKT_MaRin_2015_WC.png',
            championships: 1,
            worldsWins: 1,
            years: '2013-2020',
            description: '2015 월즈 우승, 월즈 MVP',
            nationality: 'KR',
            league: 'LCK',
            seasons: ['S5'],
            seasonTeam: 'SKT T1 (S5)'
        },
        {
            id: 'smeb',
            name: 'Smeb',
            realName: '송경호',
            team: 'ROX Tigers',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/8/8e/ROX_Smeb_2016_WC.png',
            championships: 2,
            worldsWins: 0,
            years: '2012-2020',
            description: 'LCK 레전드 탑라이너',
            nationality: 'KR',
            league: 'LCK',
            seasons: ['S6'],
            seasonTeam: 'ROX Tigers (S6)'
        },
        {
            id: 'khan',
            name: 'Khan',
            realName: '김동하',
            team: 'DAMWON Gaming',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/5/5c/DK_Khan_2021_Split_1.png',
            championships: 3,
            worldsWins: 1,
            years: '2017-2022',
            description: '2021 월즈 우승',
            nationality: 'KR',
            league: 'LCK',
            seasons: ['S11'],
            seasonTeam: 'DWG KIA (S11)'
        },
        {
            id: 'kiin',
            name: 'Kiin',
            realName: '김기인',
            team: 'Afreeca Freecs',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/f/f9/KDF_Kiin_2023_Split_2.png',
            championships: 0,
            worldsWins: 0,
            years: '2017-현재',
            description: '최고의 무관 탑라이너',
            nationality: 'KR',
            league: 'LCK',
            seasons: ['S8', 'S9', 'S10', 'S11', 'S12', 'S13', 'S14'],
            seasonTeam: 'KDF (S12)'
        },
        {
            id: 'nuguri',
            name: 'Nuguri',
            realName: '장하권',
            team: 'DAMWON Gaming',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/e/e5/DWG_Nuguri_2020_WC.png',
            championships: 2,
            worldsWins: 1,
            years: '2018-현재',
            description: '2020 월즈 우승',
            nationality: 'KR',
            league: 'LCK',
            seasons: ['S9', 'S10', 'S12'],
            seasonTeam: 'DWG KIA (S12)'
        },
        {
            id: 'zeus',
            name: 'Zeus',
            realName: '최우제',
            team: 'T1',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/a/a0/T1_Zeus_2023_WC.png',
            championships: 3,
            worldsWins: 1,
            years: '2021-현재',
            description: '2023 월즈 우승',
            nationality: 'KR',
            league: 'LCK',
            seasons: ['S12', 'S13', 'S14'],
            seasonTeam: 'T1 (S12)'
        },
        {
            id: 'doran',
            name: 'Doran',
            realName: '최현준',
            team: 'Gen.G',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/7/71/GEN_Doran_2024_Split_1.png',
            championships: 2,
            worldsWins: 1,
            years: '2019-현재',
            description: '2024 월즈 우승',
            nationality: 'KR',
            league: 'LCK',
            seasons: ['S12', 'S13', 'S14'],
            seasonTeam: 'Gen.G (S12)'
        }
    ],
    jungle: [
        {
            id: 'bengi',
            name: 'Bengi',
            realName: '배성웅',
            team: 'SKT T1',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/1/10/SKT_Bengi_2016_WC.png',
            championships: 5,
            worldsWins: 3,
            years: '2013-2017',
            description: '3회 월즈 우승, 정글의 신',
            nationality: 'KR',
            league: 'LCK',
            seasons: ['S3', 'S5', 'S6'],
            seasonTeam: 'SKT T1 (S6)'
        },
        {
            id: 'score',
            name: 'Score',
            realName: '고동빈',
            team: 'KT Rolster',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/c/c4/KT_Score_2018_WC.png',
            championships: 1,
            worldsWins: 0,
            years: '2012-2019',
            description: '정글 레전드',
            nationality: 'KR',
            league: 'LCK',
            seasons: ['S7', 'S8'],
            seasonTeam: 'KT Rolster (S8)'
        },
        {
            id: 'peanut',
            name: 'Peanut',
            realName: '한왕호',
            team: 'Gen.G',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/1/1e/GEN_Peanut_2023_WC.png',
            championships: 4,
            worldsWins: 1,
            years: '2015-현재',
            description: '2024 월즈 우승',
            nationality: 'KR',
            league: 'LCK',
            seasons: ['S6', 'S7', 'S8', 'S9', 'S12', 'S13', 'S14'],
            seasonTeam: 'Gen.G (S12)'
        },
        {
            id: 'canyon',
            name: 'Canyon',
            realName: '김건부',
            team: 'DAMWON Gaming',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/a/a0/DK_Canyon_2021_Split_1.png',
            championships: 4,
            worldsWins: 1,
            years: '2019-현재',
            description: '2020 월즈 우승, 정글 괴물',
            nationality: 'KR',
            league: 'LCK',
            seasons: ['S9', 'S10', 'S11', 'S12', 'S13', 'S14'],
            seasonTeam: 'DWG KIA (S12)'
        },
        {
            id: 'oner',
            name: 'Oner',
            realName: '문현준',
            team: 'T1',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/6/63/T1_Oner_2023_WC.png',
            championships: 3,
            worldsWins: 1,
            years: '2021-현재',
            description: '2023 월즈 우승',
            nationality: 'KR',
            league: 'LCK',
            seasons: ['S11', 'S12', 'S13', 'S14'],
            seasonTeam: 'T1 (S12)'
        },
        {
            id: 'clid',
            name: 'Clid',
            realName: '김태민',
            team: 'SKT T1',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/8/81/SKT_Clid_2019_Split_1.png',
            championships: 2,
            worldsWins: 0,
            years: '2018-현재',
            description: '공격적인 정글링',
            nationality: 'KR',
            league: 'LCK',
            seasons: ['S9', 'S10', 'S11', 'S12'],
            seasonTeam: 'Hanwha Life (S12)'
        },
        {
            id: 'tarzan',
            name: 'Tarzan',
            realName: '이승용',
            team: 'Griffin',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/8/84/GRF_Tarzan_2019_WC.png',
            championships: 0,
            worldsWins: 0,
            years: '2018-현재',
            description: '정글 천재',
            nationality: 'KR',
            league: 'LPL',
            seasons: ['S9', 'S10', 'S11', 'S12', 'S13'],
            seasonTeam: 'LNG (S12)'
        }
    ],
    mid: [
        {
            id: 'faker',
            name: 'Faker',
            realName: '이상혁',
            team: 'T1',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/d/d4/T1_Faker_2023_WC.png',
            championships: 10,
            worldsWins: 4,
            years: '2013-현재',
            description: '4회 월즈 우승, GOAT',
            nationality: 'KR',
            league: 'LCK',
            seasons: ['S3', 'S5', 'S6', 'S12', 'S13', 'S14'],
            seasonTeam: 'T1 (S12)'
        },
        {
            id: 'dopa',
            name: 'Dopa',
            realName: '정상길',
            team: 'Solo Queue',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/5/56/Dopa.jpg',
            championships: 0,
            worldsWins: 0,
            years: '-',
            description: '솔로랭크의 신',
            nationality: 'KR',
            league: 'KR SoloQ',
            seasons: ['S5'],
            seasonTeam: 'Solo Queue'
        },
        {
            id: 'rookie',
            name: 'Rookie',
            realName: '송의진',
            team: 'KT Rolster',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/8/86/IG_Rookie_2018_WC.png',
            championships: 1,
            worldsWins: 1,
            years: '2014-현재',
            description: '2018 월즈 우승 (IG)',
            nationality: 'CN',
            league: 'LPL',
            seasons: ['S4', 'S8', 'S9', 'S12'],
            seasonTeam: 'IG (S12)'
        },
        {
            id: 'bdd',
            name: 'BDD',
            realName: '곽보성',
            team: 'Gen.G',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/6/6e/GEN_BDD_2023_Split_2.png',
            championships: 2,
            worldsWins: 0,
            years: '2016-현재',
            description: 'LCK 미드 레전드',
            nationality: 'KR',
            league: 'LCK',
            seasons: ['S7', 'S8', 'S9', 'S10', 'S11', 'S12', 'S13', 'S14'],
            seasonTeam: 'NS RedForce (S12)'
        },
        {
            id: 'chovy',
            name: 'Chovy',
            realName: '정지훈',
            team: 'Gen.G',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/b/bc/GEN_Chovy_2023_WC.png',
            championships: 2,
            worldsWins: 1,
            years: '2018-현재',
            description: '2024 월즈 우승, 라인전의 신',
            nationality: 'KR',
            league: 'LCK',
            seasons: ['S9', 'S10', 'S11', 'S12', 'S13', 'S14'],
            seasonTeam: 'Gen.G (S12)'
        },
        {
            id: 'showmaker',
            name: 'ShowMaker',
            realName: '허수',
            team: 'DAMWON Gaming',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/e/e3/DK_ShowMaker_2021_Split_1.png',
            championships: 3,
            worldsWins: 1,
            years: '2018-현재',
            description: '2020 월즈 우승',
            nationality: 'KR',
            league: 'LCK',
            seasons: ['S9', 'S10', 'S11', 'S12', 'S13', 'S14'],
            seasonTeam: 'DWG KIA (S12)'
        },
        {
            id: 'caps',
            name: 'Caps',
            realName: 'Rasmus Winther',
            team: 'G2 Esports',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/4/4b/G2_Caps_2019_WC.png',
            championships: 0,
            worldsWins: 0,
            years: '2017-현재',
            description: 'EU 미드 레전드',
            nationality: 'DK',
            league: 'LEC',
            seasons: ['S8', 'S9', 'S10', 'S11', 'S12', 'S13', 'S14'],
            seasonTeam: 'G2 (S12)'
        }
    ],
    adc: [
        {
            id: 'bang',
            name: 'Bang',
            realName: '배준식',
            team: 'SKT T1',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/7/71/SKT_Bang_2016_WC.png',
            championships: 5,
            worldsWins: 2,
            years: '2014-현재',
            description: '2회 월즈 우승',
            nationality: 'KR',
            league: 'LCK',
            seasons: ['S5', 'S6', 'S7', 'S8'],
            seasonTeam: 'SKT T1 (S6)'
        },
        {
            id: 'pray',
            name: 'PraY',
            realName: '김종인',
            team: 'ROX Tigers',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/0/0a/ROX_PraY_2016_WC.png',
            championships: 2,
            worldsWins: 0,
            years: '2012-2019',
            description: 'ADC 레전드',
            nationality: 'KR',
            league: 'LCK',
            seasons: ['S4', 'S5', 'S6'],
            seasonTeam: 'ROX Tigers (S6)'
        },
        {
            id: 'deft',
            name: 'Deft',
            realName: '김혁규',
            team: 'DRX',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/8/88/DRX_Deft_2022_WC.png',
            championships: 3,
            worldsWins: 1,
            years: '2013-2023',
            description: '2022 월즈 우승',
            nationality: 'KR',
            league: 'LCK',
            seasons: ['S4', 'S6', 'S8', 'S12'],
            seasonTeam: 'DRX (S12)'
        },
        {
            id: 'ruler',
            name: 'Ruler',
            realName: '박재혁',
            team: 'Gen.G',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/e/e5/GEN_Ruler_2023_WC.png',
            championships: 2,
            worldsWins: 1,
            years: '2016-현재',
            description: '2017 월즈 우승 (SSG)',
            nationality: 'KR',
            league: 'LCK',
            seasons: ['S7', 'S10', 'S12', 'S13'],
            seasonTeam: 'Gen.G (S12)'
        },
        {
            id: 'teddy',
            name: 'Teddy',
            realName: '박진성',
            team: 'T1',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/5/5c/T1_Teddy_2021_Split_1.png',
            championships: 2,
            worldsWins: 0,
            years: '2017-현재',
            description: 'CS의 신',
            nationality: 'KR',
            league: 'LCK',
            seasons: ['S9', 'S10', 'S11'],
            seasonTeam: 'T1 (S10)'
        },
        {
            id: 'gumayusi',
            name: 'Gumayusi',
            realName: '이민형',
            team: 'T1',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/c/c8/T1_Gumayusi_2023_WC.png',
            championships: 2,
            worldsWins: 1,
            years: '2020-현재',
            description: '2023 월즈 우승',
            nationality: 'KR',
            league: 'LCK',
            seasons: ['S11', 'S12', 'S13', 'S14'],
            seasonTeam: 'T1 (S12)'
        },
        {
            id: 'peyz',
            name: 'Peyz',
            realName: '김수환',
            team: 'Gen.G',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/5/5a/GEN_Peyz_2024_Split_1.png',
            championships: 1,
            worldsWins: 1,
            years: '2023-현재',
            description: '2024 월즈 우승',
            nationality: 'KR',
            league: 'LCK',
            seasons: ['S14'],
            seasonTeam: 'Gen.G (S14)'
        }
    ],
    support: [
        {
            id: 'wolf',
            name: 'Wolf',
            realName: '이재완',
            team: 'SKT T1',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/6/6c/SKT_Wolf_2016_WC.png',
            championships: 5,
            worldsWins: 2,
            years: '2014-2019',
            description: '2회 월즈 우승',
            nationality: 'KR',
            league: 'LCK',
            seasons: ['S5', 'S6', 'S7'],
            seasonTeam: 'SKT T1 (S6)'
        },
        {
            id: 'gorilla',
            name: 'GorillA',
            realName: '강범현',
            team: 'ROX Tigers',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/f/fa/ROX_GorillA_2016_WC.png',
            championships: 2,
            worldsWins: 0,
            years: '2012-2020',
            description: '서포터 레전드',
            nationality: 'KR',
            league: 'LCK',
            seasons: ['S5', 'S6'],
            seasonTeam: 'ROX Tigers (S6)'
        },
        {
            id: 'mata',
            name: 'Mata',
            realName: '조세형',
            team: 'Samsung White',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/0/0f/SSW_Mata_2014_WC.png',
            championships: 3,
            worldsWins: 1,
            years: '2013-2020',
            description: '2014 월즈 우승, 서포터 GOAT',
            nationality: 'KR',
            league: 'LCK',
            seasons: ['S4', 'S5', 'S6'],
            seasonTeam: 'SSW (S4)'
        },
        {
            id: 'beryl',
            name: 'BeryL',
            realName: '조건희',
            team: 'DAMWON Gaming',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/e/eb/DK_BeryL_2021_Split_1.png',
            championships: 2,
            worldsWins: 1,
            years: '2018-현재',
            description: '2020 월즈 우승',
            nationality: 'KR',
            league: 'LCK',
            seasons: ['S10', 'S11', 'S12', 'S13'],
            seasonTeam: 'DRX (S12)'
        },
        {
            id: 'keria',
            name: 'Keria',
            realName: '류민석',
            team: 'T1',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/1/1d/T1_Keria_2023_WC.png',
            championships: 3,
            worldsWins: 1,
            years: '2020-현재',
            description: '2023 월즈 우승, 천재 서포터',
            nationality: 'KR',
            league: 'LCK',
            seasons: ['S11', 'S12', 'S13', 'S14'],
            seasonTeam: 'T1 (S12)'
        },
        {
            id: 'lehends',
            name: 'Lehends',
            realName: '손시우',
            team: 'Gen.G',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/d/dd/GEN_Lehends_2023_WC.png',
            championships: 2,
            worldsWins: 1,
            years: '2018-현재',
            description: '2024 월즈 우승',
            nationality: 'KR',
            league: 'LCK',
            seasons: ['S10', 'S12', 'S13', 'S14'],
            seasonTeam: 'Gen.G (S12)'
        },
        {
            id: 'corejj',
            name: 'CoreJJ',
            realName: '조용인',
            team: 'Samsung Galaxy',
            image: 'https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/c/c9/SSG_CoreJJ_2017_WC.png',
            championships: 1,
            worldsWins: 1,
            years: '2014-현재',
            description: '2017 월즈 우승',
            nationality: 'KR',
            league: 'LCS',
            seasons: ['S7', 'S8', 'S9', 'S10', 'S11', 'S12', 'S13', 'S14'],
            seasonTeam: 'Team Liquid (S12)'
        }
    ]
};

// Export for use in script.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = players;
}
